gallerysite/gallery/urls.py
from django.conf.urls import url
from . import views
from .views import Categorylist, ResultList, ImageDetail
from django.conf import settings
from django.conf.urls.static import static

app_name = 'GALLERY'
urlpatterns = [
    url(r'^$', Categorylist.as_view()),
    url(r'^([\d]+)/$', ResultList.as_view()),
    url(r'^(?P<category_id>[0-9]+)/(?P<pk>[0-9]+)/$', ImageDetail.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallerysite/gallerysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gallery.urls')),
]

gallerysite/gallery/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Image(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    item = models.ImageField(upload_to = 'gallery')
    publication_date = models.DateTimeField('Publication Date')

    def __str__(self):
        return self.name

gallerysite/gallery/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Category, Image
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404

class Categorylist(ListView):
    template_name = 'gallery/index.html'
    context_object_name = 'list_categories'
    queryset = Category.objects.order_by('-name')

class ResultList(ListView):
    template_name = 'gallery/results.html'

    def get_queryset(self):
        category = get_object_or_404(Category, id=self.args[0])
        return Image.objects.filter(category = category)

class ImageDetail(DetailView):
    model = Image
    template_name = 'gallery/detail.html'
    context_object_name = 'image_detail'
    def get_context_data(self, **kwargs):
        context = super(ImageDetail, self).get_context_data(**kwargs)
        return context

gallerysite/gallery/templates/gallery/detail.html
<ul>
    <li>
        <div>
            <h1> 
                {{object.name}}
            </h1>
            <a href="/{{ object.category.id }}/">{{ object.category.name }}</a>
            <br>
                <img src="{{ object.item.url }}" width=300px />
        </div>
    </li>
</ul>

gallerysite/gallery/templates/gallery/index.html
{% if list_categories %}
    <ul>
    {% for category in list_categories %}
        <li><a href="/{{ category.id }}/">{{ category.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No categories are available.</p>
{% endif %}

gallerysite/gallery/templates/gallery/results.html
{% if image_list %}
    <ul>
    {% for image in image_list %}
        <li>
            <div>
                <h1> 
                    {{image.name}}
                </h1>
                <a href="/{{ image.category.id }}/">{{ image.category.name }}</a>
                <br>
                <a href='/{{ image.category.id }}/{{ image.id }}/'>
                    <img src="{{ image.item.url }}" width=300px />
                </a>
            </div>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Image are available.</p>
{% endif %}